import json

file_path = 'app/routers/bible.py'
with open(file_path, 'r', encoding='utf-8') as f:
    text = f.read()

# 17-20: 6 questions each.
# 21-23: 9 questions each.
q_bank = {
    "17_helm_charts": [
        {"q": "What happens if a Helm release includes a `pre-upgrade` hook that strictly produces a non-zero exit code on failure, and it fails?", "options": ["Helm retries infinitely", "Helm aborts the deployment and leaves the release in a 'failed' state while preserving the previous deployment objects", "Helm rolls back automatically", "Helm ignores it"], "a": 1},
        {"q": "Inside a Helm template, what is the precise purpose of the `required` function syntax (e.g. `{{ required \"Password is required!\" .Values.dbPass }}`)?", "options": ["To encrypt the password", "To fail the template rendering explicitly during compilation if the user did not supply the mandatory Value in `values.yaml` or `--set`", "To pull data from K8s secrets", "To generate a random password"], "a": 1},
        {"q": "If you add `helm.sh/hook-delete-policy: hook-succeeded` to a Job manifest, what happens?", "options": ["The job runs forever", "The K8s garbage collector deletes the Job object ONLY after it completes successfully, preventing clutter from temporary migration pods", "It deletes the pod if it crashes", "It deletes the Helm chart"], "a": 1},
        {"q": "How does Helm v3 natively differ from Kustomize when handling YAML variants?", "options": ["Helm uses explicit text templating (Go templates), whereas Kustomize uses a base-and-overlay patching strategy without touching the original YAML lines", "Helm is for Ansible", "Kustomize uses Python", "They are identical"], "a": 0},
        {"q": "What specific file inside a Chart controls dependencies dynamically fetched from other remote Helm repositories?", "options": ["dependencies.yaml", "values.yaml", "requirements.txt", "Chart.yaml"], "a": 3},
        {"q": "What command strictly verifies the internal structural integrity and templating validity of your local `.tgz` Helm package without contacting a cluster?", "options": ["helm install", "helm test", "helm lint", "helm diff"], "a": 2}
    ],
    "18_advanced_tf": [
        {"q": "When deploying Terragrunt at scale across hundreds of AWS Accounts, what is the safest way to orchestrate role assumption?", "options": ["Hardcode root keys", "Utilize OIDC authentication from the CI/CD pipeline pointing directly to the target Account's IAM Cross-Account roles via native backend trust policies", "Store keys in GitHub", "Use an EC2 instance profile on a bastion host"], "a": 1},
        {"q": "If someone accidentally breaks the `.terragrunt-cache` directory locally, what is the immediate resolution?", "options": ["Run apply", "Format the drive", "You simply delete the cache directory entirely and run `terragrunt init` again to re-download the remote modules", "It cannot be fixed"], "a": 2},
        {"q": "What mechanism does Infracost use to map specific Terraform resources to real-world cloud billing prices dynamically?", "options": ["Regex matching", "Infracost parses the proprietary TF execution plan JSON, matches the schema IDs against its Cloud Pricing API graph, and calculates hourly metrics", "It scrapes the AWS Console", "It uses Cost Explorer"], "a": 1},
        {"q": "How does the `tflint` engine differ from the native `terraform validate`?", "options": ["`terraform validate` just checks HCL syntax and internal references. `tflint` dynamically queries cloud provider APIs to ensure validity against reality (e.g., verifying if an EC2 instance class actually exists built-in).", "They are the exact same", "`tflint` costs money", "Validation is deprecated"], "a": 0},
        {"q": "Why is utilizing Terraform CDK over raw HCL sometimes viewed as risky in strict highly-regulated enterprises?", "options": ["CDK is slower", "Generative Python/TS CDK code creates an abstraction layer. Debugging complex state failures often forces engineers to reverse-engineer thousands of lines of auto-synthesized HCL JSON instead of directly reading readable config files.", "It does not support AWS", "It uses Docker"], "a": 1},
        {"q": "What is the primary architectural function of Terragrunt's `generate` block?", "options": ["To make code", "To dynamically write `.tf` files (like standardized provider block definitions or backend configs) into child directories before Terraform is executed, enforcing DRY configuration", "To generate passwords", "To deploy pods"], "a": 1}
    ],
    "19_advanced_ansible": [
        {"q": "If you define an `ansible.builtin.assert` block inside a CI pipeline and it fails, what happens to the pipeline execution?", "options": ["The pipeline is ignored", "Ansible throws a fatal error and produces a non-zero exit code, physically halting the Jenkins/GitLab pipeline execution step", "It emails the admin", "It skips the host"], "a": 1},
        {"q": "Inside an Execution Environment (EE), what is `ansible-builder` specifically used for?", "options": ["Editing YAML", "Parsing Dockerfiles incrementally to dynamically construct the container image encapsulating `ansible-core`, Python libraries, and mapped Collections", "Running the playbook", "Configuring passwords"], "a": 1},
        {"q": "When configuring AWS inventory generation via `aws_ec2.yml`, what is the precise parameter that stops Ansible from caching the inventory indefinitely?", "options": ["refresh: true", "flush_cache: true", "cache_timeout: <seconds>", "cache: false"], "a": 2},
        {"q": "In massive horizontal scaling (e.g. 5,000 servers), why does SSH multiplexing (ControlMaster) substantially drop playbook execution latency?", "options": ["It compresses the payload", "It reuses an existing, persistent TCP/SSH connection socket for multiple consecutive module executions, bypassing the heavy cryptographic SSH handshake overhead for every single task", "It removes encryption", "It runs Python locally"], "a": 1},
        {"q": "If you are targeting a Windows endpoint, what implicit transport layer protocol natively guarantees encrypted configuration logic delivery?", "options": ["SSHv2", "WinRM functioning over HTTPS port 5986", "SNMP", "TCP Port 80"], "a": 1},
        {"q": "What specifically separates Ansible Automation Platform (AAP/Tower) from generic cron-based Ansible executions?", "options": ["AAP uses Go", "AAP introduces Role-Based Access Control (RBAC), credential masking, execution environment isolation per team, and granular REST API scheduling.", "AAP is free", "AAP destroys faster"], "a": 1}
    ],
    "20_advanced_k8s": [
        {"q": "When implementing ArgoCD inside an On-Premise bare-metal cluster, what fundamentally prevents external firewalls from blocking deployments?", "options": ["ArgoCD uses Ping", "ArgoCD utilizes a highly secure Pull Model: it initiates outbound TCP/443 requests from the internal cluster out to Github, effectively bypassing inbound NAT/Firewall blocks", "We use VPNs", "ArgoCD opens Port 22"], "a": 1},
        {"q": "If Cilium is acting as the CNI and entirely replacing kube-proxy, how does it process `ClusterIP` network routing without IPTables?", "options": ["DNS spoofing", "It dynamically compiles socket-layer BPF programs inserted directly into the Linux kernel networking stack algorithms, natively translating DNAT operations via high-performance maps", "It routes traffic through a physical switch", "It relies on Docker"], "a": 1},
        {"q": "Under the SPIFFE/SPIRE architecture in Kubernetes, what cryptographic object is generated to prove a Pod's Identity (SVID)?", "options": ["A Basic Auth password", "An ephemeral, strictly-scoped X.509 Certificate or JWT token automatically rotated by the SPIRE agent on the node", "An AWS IAM Key", "An SSL cert valid for 10 years"], "a": 1},
        {"q": "How does Karpenter fundamentally differ from the standard Cluster Autoscaler (CAS)?", "options": ["Karpenter is slower", "Karpenter dynamically calculates pod constraints and requests JUST-IN-TIME bare-metal/EC2 instances that exclusively fit those dimensions without mimicking traditional Node Groups or ASGs", "Karpenter uses Python", "They are identical"], "a": 1},
        {"q": "In an eBPF observability stack, what does Hubble natively provide over traditional Prometheus scraping?", "options": ["It stores logs forever", "It provides highly-granular L3/L4/L7 flow visibility directly from the kernel dataplane without modifying application code or deploying heavy sidecar proxies", "It formats YAML", "It sends cheaper metrics"], "a": 1},
        {"q": "If an ArgoCD application object reads an `OutOfSync` condition, what precisely does it mean?", "options": ["The cluster is down", "The actual deployed objects inside Kubernetes differ systematically from the declarative YAML stored in the monitored Git repository", "The Github repo is offline", "Docker is full"], "a": 1}
    ],
    "21_interview_tf": [
        {"q": "If a provider changes their API violently and a Terraform resource becomes permanently corrupted in your state (`terraform apply` constantly crashes on deserialization), how do you forcefully evict it?", "options": ["terraform delete", "terraform force-unlock", "Delete the .tf file", "terraform state rm <resource_identifier>"], "a": 3},
        {"q": "What happens if two Jenkins pipelines execute `terraform apply` simultaneously using the SAME local state file location (no backend)?", "options": ["Terraform creates a lock.", "Data corruption. The processes will aggressively overwrite the local JSON file simultaneously, causing massive graph serialization faults.", "Wait, then apply.", "It merges the files."], "a": 1},
        {"q": "Explain how to circumvent the 'Provider Configuration Invalid' error when the provider logic fundamentally requires values that are dynamically created during the same apply.", "options": ["Use external scripts", "Terraform architecture inherently restricts this. You must use decoupled deployments (e.g. Terragrunt layers), deploying the dependencies first, writing to state, and pulling them as purely static inputs in the lower-tier module.", "Write a bash script", "Use the `-refresh` flag"], "a": 1},
        {"q": "When writing reusable code, why do Senior Engineers favor `optional(string)` arguments inside object variable constraint types?", "options": ["It looks cleaner", "It drastically reduces configuration footprint for module consumers by establishing deep native default schemas inside heavily nested dictionaries.", "It saves AWS costs", "It hides secrets"], "a": 1},
        {"q": "In a scenario involving thousands of security rules, what Terraform primitive minimizes JSON payload sizes to AWS?", "options": ["Multiple Security Group modules", "A single dynamic block wrapped in an aggregate rule API payload, compressing massive independent HCL logic into one serialized JSON API push.", "Count arrays", "It doesn't matter."], "a": 1},
        {"q": "How do you forcefully intercept state migrations when upgrading from Terraform version 0.12 to 1.5 across breaking changes?", "options": ["Use `terraform init -upgrade` iteratively through middle versions (e.g. 0.13, 0.14) because state file formats shifted strictly between generations.", "You don't, you just use 1.5.", "Change the text in state.", "Re-apply everything."], "a": 0},
        {"q": "What occurs when the `create_before_destroy` lifecycle parameter triggers an AWS IP collision?", "options": ["Terraform aborts.", "The plan evaluates cleanly, but the apply forces a destructive hard-crash midway during the CREATE phase, stranding the environment gracefully.", "AWS modifies the quota.", "It overwrites the IP."], "a": 1},
        {"q": "What is the structural risk of using `data` sources aggressively for dynamic dependencies like VPC IDs across thousands of nodes?", "options": ["It doesn't matter", "They trigger API rate-limiting issues implicitly during the `terraform plan` phase because Terraform pulls the data synchronously before establishing the graph execution.", "It deletes nodes.", "It bypasses IAM."], "a": 1},
        {"q": "How do you correctly handle external third-party Terraform providers not found in the HashiCorp registry inside a strict Air-Gapped enterprise?", "options": ["Download manually.", "Configure a filesystem mirror using `provider_installation` block mapping in `.terraformrc`, pointing to a local directory loaded with the pre-compiled checksummed binaries.", "Contact HashiCorp.", "You cannot."], "a": 1}
    ],
    "22_interview_ansible": [
        {"q": "If you deploy an Ansible Playbook heavily relying on `ansible_env` facts, what happens if the target machine utilizes a restricted `/bin/sh` shell environment?", "options": ["It works normally.", "The facts return blank.", "The playbook fundamentally fails execution errors due to native Python parsing breaking over missing baseline variables injected natively by full POSIX shells (like bash).", "It changes permissions."], "a": 2},
        {"q": "Explain how to circumvent standard SSH latency constraints natively within the Ansible `ansible.cfg` when processing 200,000 files.", "options": ["Use the `strategy: free` to bypass linear host sequencing, immediately paired with `pipelining = True` to halt multi-stage directory pushes.", "Buy faster servers.", "Use an agent.", "Compress the files manually."], "a": 0},
        {"q": "What is the architectural impact of changing the execution strategy from `linear` to `free` in a rolling deployment?", "options": ["It doesn't change anything.", "The playbook abandons synchronization. Hosts race to the end individually without waiting for other nodes to complete the current horizontal task layer, destroying rolling consistency.", "It crashes Jenkins.", "It costs more CPU."], "a": 1},
        {"q": "If a Vault password is provided via a python script (`--vault-password-file script.py`), what exact security requirement exists on the script file?", "options": ["None.", "It must be executable by the user invoking Ansible, and output the raw plaintext password exclusively to stdout upon invocation.", "It must be encrypted.", "It must use Docker."], "a": 1},
        {"q": "What occurs when multiple developers push distinct Ansible `roles` utilizing conflicting internal variable structures without using role prefixes?", "options": ["Syntax error.", "Global Variable Namespace Collisions. Because variables scope globally in playbooks, the last-loaded role violently overwrites the previous variables, causing silent logic shifts without failing.", "It skips the roles.", "Docker isolates them."], "a": 1},
        {"q": "When writing custom Python modules for Ansible, what native method allows seamless JSON payload streaming back to the controller?", "options": ["print()", "sys.exit()", "The built-in `AnsibleModule.exit_json()` library call seamlessly translates the dictionary into standardized stdout structures.", "Writing to a file."], "a": 2},
        {"q": "In high-security networks utilizing Bastion Hosts, how is Ansible architected to dynamically traverse the proxy natively?", "options": ["It uses VPNs.", "Configuring `ProxyJump` proxy commands implicitly within the `ansible_ssh_common_args` parameter within the dynamic inventory definition.", "It cannot bypass proxies.", "It installs an agent on the bastion."], "a": 1},
        {"q": "What is the consequence of utilizing the `template` module aggressively inside a high-frequency `for_each` loop spanning 5,000 strings?", "options": ["It finishes quickly.", "It destroys the control node.", "Catastrophic CPU saturation on the Automation controller, as the Jinja2 rendering engine evaluates the templating tree syntactically *before* the SSH distribution phase.", "It formats YAML automatically."], "a": 2},
        {"q": "How does AAP (Tower) implicitly guarantee playbook consistency if the underlying Linux OS libraries of the execution node routinely change?", "options": ["It ignores changes.", "Through Execution Environments. Playbooks operate strictly inside deterministic OCI-compliant Podman containers loaded securely via immutable registries.", "It installs packages locally.", "It uses Terraform."], "a": 1}
    ],
    "23_interview_k8s": [
        {"q": "When a worker node suffers a kernel panic, what specific K8s component is responsible for permanently marking the node as Dead, and how long is the generic default timeout?", "options": ["The Kubelet, 5 seconds.", "The Node Controller (running within kube-controller-manager), defaulting around 40 seconds before initiating eviction sequences.", "Docker, 5 minutes.", "The APIServer, instantly."], "a": 1},
        {"q": "Explain the architectural consequence inside etcd when you violently hit the default 2MB transaction limit boundary during a massive API injection.", "options": ["It crashes.", "etcd throws the `etcdserver: request is too large` exception. The operation halts deterministically across the Raft quorum to prevent unpredictable database state bloat.", "It parses the data perfectly.", "It writes to the disk."], "a": 1},
        {"q": "What occurs if an Operator's custom controller possesses an unoptimized reconciliation loop that lacks jitter bounds?", "options": ["It scales infinitely.", "It triggers a widespread 'Thundering Herd' DDoSing the Kube-APIServer aggressively during cluster restarts as thousands of objects continuously demand synchronization polling.", "It ignores the queue.", "It deletes nodes."], "a": 1},
        {"q": "How does `cert-manager` dynamically circumvent DNS propagation latency issues when executing ACME DNS-01 challenges heavily across massive domains?", "options": ["It doesn't.", "Using AWS Route53.", "It actively modifies its logic to query the Authoritative Nameservers directly mimicking split-horizon detection to ensure rapid token availability before validating.", "It uses HTTP verification."], "a": 2},
        {"q": "When utilizing native Kubernetes Headless Services (`clusterIP: None`), what is fundamentally altered at the DNS translation layer?", "options": ["It acts identically.", "It removes the proxy abstraction completely, forcing CoreDNS to return the explicit raw IP addresses of all underlying Ready Pods back directly to the client endpoint for client-side load balancing.", "It denies traffic.", "It uses NodePort."], "a": 1},
        {"q": "Describe the core consequence of implementing highly complex OPA Gatekeeper logic evaluating strictly at the ValidatingAdmissionWebhook phase across 5,000 pods.", "options": ["It works fine.", "If the underlying policy logic requires external API lookups outside the cluster boundary, you instantly incur severe latency, bottlenecking all cluster scaling execution and creating massive timeouts.", "It crashes Docker.", "It logs to Slack."], "a": 1},
        {"q": "If a StatefulSet requires an immediate, forceful rollback crossing an immutable volume constraint, what is the required operational pattern?", "options": ["Apply `terraform destroy`.", "Manually unbinding and backing up the underlying PV constraints, completely deleting the active StatefulSet via `cascade=orphan`, patching PVCs, and recreating matching labels.", "Applying `helm refresh`.", "Waiting for etcd."], "a": 1},
        {"q": "In high-performance analytical environments, what limits the capability of standard kube-proxy IPVS load balancing logic?", "options": ["It lacks UDP.", "The inherent lack of DSR (Direct Server Return) architectures seamlessly integrated. Processing massive multi-gigabit traffic strictly within conventional translation pipelines bogs down node network namespaces severely.", "It relies strictly on Terraform.", "It runs entirely on Python."], "a": 1},
        {"q": "What specific consequence emerges functionally when integrating Kustomize multi-layer patching aggressively against conflicting Helm Chart hooks defined by third vendors?", "options": ["Helm wins out.", "Kustomize entirely strips or violently alters annotations blindly before execution, frequently crippling Helm's intrinsic pre/post rendering verification states.", "It merges cleanly.", "Kustomize ignores Helm."], "a": 1}
    ]
}

def inject():
    global text
    for ch_id, questions in q_bank.items():
        idx = text.find(f'"id": "{ch_id}"')
        if idx == -1: continue
        quiz_end = text.find('        ],', idx)
        if quiz_end == -1: continue
        
        block = text[idx:quiz_end]
        has_items = '{' in block[block.find('"quiz": ['):]
        
        insert_str = ""
        for q in questions:
            if not has_items and insert_str == "":
                insert_str += f'\n            {json.dumps(q)}'
                has_items = True # Set to true so next iteration adds a comma
            else:
                insert_str += f',\n            {json.dumps(q)}'
                
        text = text[:quiz_end] + insert_str + '\n' + text[quiz_end:]

inject()

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(text)

print("Part 3 Executed Successfully.")
