import json
import re

file_path = 'app/routers/bible.py'
with open(file_path, 'r', encoding='utf-8') as f:
    text = f.read()

q_bank = {
    "01_intro": [
        {"q": "How does Terraform calculate the checksums placed in `.terraform.lock.hcl`?", "options": ["SHA256 of the zip file", "SHA256 of the extracted binary and zip using h1/zh tags", "MD5 of the provider binary", "A random hash from Hashicorp"], "a": 1},
        {"q": "What happens if a resource is modified outside Terraform AND someone modifies the HCL code to a third conflicting state before running an apply?", "options": ["Terraform crashes", "Terraform forces a manual merge", "Terraform refreshes state to the raw reality, diffs against the HCL, and applies the HCL desired state", "Terraform ignores the HCL"], "a": 2},
        {"q": "Can you use dynamic logic (like counts) to instantiate `provider` blocks?", "options": ["Yes, using for_each", "Yes, using count", "No, provider configurations must be static", "Yes, using nested modules"], "a": 2},
        {"q": "When writing to the local backend, how does Terraform ensure acid compliance on the state file?", "options": ["fsync and atomic file renames", "SQLite transactions", "AWS DynamoDB", "It doesn't"], "a": 0},
        {"q": "What is the primary technical drawback of the `depends_on` meta-argument?", "options": ["It causes circular dependencies", "It disables Terraform's concurrent graph execution for those nodes, heavily slowing down apply times", "It costs money", "It breaks state locks"], "a": 1},
        {"q": "If you misspell a resource type, at what specific phase does Terraform catch the error?", "options": ["terraform init", "terraform plan", "terraform validate or plan parsing phase", "terraform apply"], "a": 2}
    ],
    "02_workflow": [
        {"q": "What does `terraform apply -replace=aws_instance.web` do?", "options": ["Renames it", "Taints the resource, forcing destruction and recreation in the current plan execution", "Upgrades the AMI", "Ignores the resource"], "a": 1},
        {"q": "When a `terraform plan` outputs `~ update in-place`, what determines if it can be done in-place or if it forces replacement?", "options": ["The cloud provider's API capabilities mapping to the resource schema fields (ForceNew attribute)", "The user's IAM permissions", "Terraform's local state file", "The version of Terraform"], "a": 0},
        {"q": "If you delete the `.terraform` folder, do you lose your infrastructure?", "options": ["Yes", "No, it only contains downloaded plugins and backend cache, which can be restored via init", "Only if it is a remote backend", "Only if using workspaces"], "a": 1},
        {"q": "What is the exact JSON structure generated by `terraform plan -out=plan.binary`?", "options": ["It is plaintext JSON", "It is heavily compressed zip archive", "It is a proprietary binary zip containing the state, config, and diff. It must be read with `terraform show -json`", "It is a Go Lang object"], "a": 2},
        {"q": "How does `terraform console` evaluate expressions without internet access?", "options": ["It parses the `.tf` files and uses the local cached state variables", "It uses an embedded V8 engine", "It guesses", "It actually requires internet access"], "a": 0},
        {"q": "What does a non-zero exit code (exactly 2) mean when running `terraform plan -detailed-exitcode`?", "options": ["Syntax error", "Success with NO changes", "Success WITH changes present (drift detected)", "Provider crash"], "a": 2}
    ],
    "03_state": [
        {"q": "In a remote S3 backend, what precisely does the DynamoDB table store?", "options": ["The actual JSON state", "A lock item with a Digest and LockID session", "The provider config", "The history of applies"], "a": 1},
        {"q": "If someone accidentally deletes the `terraform.tfstate` from S3 and you have NO versioning, how do you recover?", "options": ["Run apply immediately", "You cannot. You must recreate empty state and manually `terraform import` every single ID back into the graph", "HashiCorp can restore it", "Run `terraform init -refresh`"], "a": 1},
        {"q": "What command allows you to rename the identity of a module inside the state file without destroying its resources?", "options": ["terraform rename", "terraform module mv", "terraform state mv module.old module.new", "terraform state replace"], "a": 2},
        {"q": "Why is manipulating the state file manually (e.g. `vim terraform.tfstate`) extremely dangerous beyond just typos?", "options": ["It breaks formatting", "It corrupts the `serial` lineage, causing remote backends to hard-reject the push", "It encrypts the file", "It locks the file permanently"], "a": 1},
        {"q": "What does `terraform force-unlock` do under the hood?", "options": ["Deletes the lock entry directly from DynamoDB/Consul", "Kills the running terraform process on another machine", "Bypasses AWS IAM", "None of the above"], "a": 0},
        {"q": "When is the `terraform state pull` command useful?", "options": ["To update providers", "To safely grab a localized JSON copy of the remote state for inspection without locking the backend", "To pull git repos", "To import resources"], "a": 1}
    ],
    "04_variables_outputs": [
        {"q": "What is the maximum allowed size of a sensitive variable output when processed by the command line?", "options": ["64kb", "There is no theoretical limit, but it will be redacted. RAM is the limit.", "1MB", "2KB"], "a": 1},
        {"q": "Can you use variables inside the `backend \"s3\" {}` block?", "options": ["Yes", "No, backend blocks are initialized before variables are parsed (interpolation is forbidden)", "Only string variables", "Only with TF Cloud"], "a": 1},
        {"q": "If you dynamically generate a variable value using `locals` and it fails validation, when does Terraform error out?", "options": ["At Apply phase", "During the syntax/parsing phase of `terraform plan` or `validate`", "During Init", "It never errors"], "a": 1},
        {"q": "Which data structure is correctly defined by this type constraint: `list(object({ name = string, tags = map(string) }))`?", "options": ["A map of strings", "An array containing dictionaries, each with a string name and an internal dictionary of strings for tags", "A string encoded as JSON", "An AWS Tag array"], "a": 1},
        {"q": "What happens if a `sensitive = true` output is referenced by a non-sensitive output?", "options": ["Terraform decrypts it", "Terraform throws a hard error indicating sensitive boundaries were breached unless you explicitly mark the recipient output as sensitive too", "It is printed in plaintext", "It is ignored"], "a": 1},
        {"q": "How can you validate an input variable to ensure it is a valid IPv4 address?", "options": ["Use the `regex()` function inside a `validation {}` block", "Use `ipv4 = true`", "Ask AWS", "Format as a number"], "a": 0}
    ],
    "05_modules": [
        {"q": "When calling a child module, how does the child pass data BACK up to the root module?", "options": ["Environment variables", "It exports the data via `output` blocks, which the root module references via `module.<name>.<output_name>`", "Shared state files", "Local files"], "a": 1},
        {"q": "Can a Terraform module call another Terraform module (Nested Modules)?", "options": ["Yes, up to infinite theoretical depth", "No", "Only once", "Only in Terraform Enterprise"], "a": 0},
        {"q": "What happens to the `.terraform` directory when you run `terraform get`?", "options": ["It deletes variables", "It forces a re-download/update of module source code referenced in the root without reinitializing providers", "It downloads cloud resources", "It gets state data"], "a": 1},
        {"q": "If you use `source = \"git::https://example.com/vpc.git?ref=v1.2.0\"`, what is Terraform doing?", "options": ["Using the public registry", "Cloning a specific git tag/branch specifically via the go-getter library to ensure exact versioning", "Downloading a zip", "Nothing"], "a": 1},
        {"q": "How do you completely remove a module and all its resources from your infrastructure?", "options": ["Just delete the file", "Remove the `module` block from HCL and run `terraform apply`, allowing Terraform to destroy the unreferenced resources", "terraform remove module", "rm -rf .terraform"], "a": 1},
        {"q": "If a module does not expose an input variable for an attribute you need to change, what must you do?", "options": ["Change it in AWS console", "Fork the module, add the variable to the module's `variables.tf` and pass it down, then update the module source", "Use a remote-exec", "Override the state"], "a": 1}
    ],
    "06_advanced_hcl": [
        {"q": "In a `for_each` loop, what do `each.key` and `each.value` represent when iterating over a `set(string)`?", "options": ["Key is index, Value is string", "Both `each.key` and `each.value` are the exact same string from the set", "Key is random, Value is string", "Sets cannot be iterated"], "a": 1},
        {"q": "What does the `try()` function do in Terraform?", "options": ["It tries to run an apply 3 times", "It evaluates multiple expressions and returns the result of the first one that does NOT produce an error", "It tests AWS API connectivity", "It catches bash script errors"], "a": 1},
        {"q": "If you want to filter a list inside a `for` expression, which keyword do you append?", "options": ["where", "filter", "if", "select"], "a": 2},
        {"q": "What is a major limitation of `count` compared to `for_each` regarding index shifting?", "options": ["Count is faster", "If you remove the middle item in a list passed to `count`, all subsequent resources shift index, causing mass destruction/recreation.", "Count uses more RAM", "None"], "a": 1},
        {"q": "When writing a `dynamic` block, what argument controls the mapping collection?", "options": ["collection", "dynamic_set", "for_each", "iterator elements"], "a": 2},
        {"q": "What is the `coalesce()` function primarily used for?", "options": ["Combining lists", "Returning the first non-null argument from a given list of arguments to establish defaults", "Encrypting strings", "Hashing passwords"], "a": 1}
    ],
    "07_testing_validation": [
        {"q": "With Terraform 1.5's native `test` framework, where do you place the test files?", "options": ["In `/tests` with `.tftest.hcl` extensions", "In a python script", "In a bash script", "In Jenkins"], "a": 0},
        {"q": "What is a `postcondition` block used for?", "options": ["Checking state after apply", "Validating the outputs of a resource *after* it is created, halting execution if the cloud provider returned invalid configurations", "Posting to slack", "Applying updates"], "a": 1},
        {"q": "If Policy as Code (OPA) returns a 'Deny' on a terraform plan JSON, what phase of the pipeline is halted?", "options": ["It blocks the Plan generation", "It halts prior to the Apply phase since the plan JSON violates security bounds", "It destroys the resources", "It sends an email but applies anyway"], "a": 1},
        {"q": "How does Terratest differ from native `terraform test`?", "options": ["Terratest uses Go and actively deploys real infrastructure to AWS, runs API checks, and then tears it down. Native testing can sometimes mock or assert without full destruction loops.", "Terratest is for Python", "They are identical", "Terratest is deprecated"], "a": 0},
        {"q": "Can you use Checkov to scan custom modules before they are invoked by the root module?", "options": ["No", "Yes, it evaluates static HCL code regardless of state", "Only with API keys", "Only in production"], "a": 1},
        {"q": "What happens if a `precondition` fails during a `terraform plan`?", "options": ["The plan is generated but throws a warning", "The plan immediately aborts and fails with a non-zero exit code", "Terraform deletes the resource", "Terraform ignores it"], "a": 1}
    ],
    "08_production": [
        {"q": "What is the absolute safest method to run Terraform in a highly-regulated enterprise production environment?", "options": ["From a developer laptop", "Terraform Cloud or a locked-down CI/CD runner (e.g. GitHub Actions) with ephemeral assumed IAM roles (OIDC) and branch-protection required reviews.", "From an EC2 bastion host", "Using hardcoded root credentials"], "a": 1},
        {"q": "How do you handle drift detection passively in production?", "options": ["Do nothing", "Set up a CRON job/Pipeline to run `terraform plan -detailed-exitcode` daily and send Slack alerts if the exit code is 2.", "Run terraform destroy every night", "Manually check AWS"], "a": 1},
        {"q": "Why is separating state files by environment and logical component (e.g. `prod/network/state`, `prod/app/state`) vital?", "options": ["To keep files small", "To isolate failure domains (Blast Radius). An error in the 'app' state won't accidentally destroy the mission-critical 'network' VPC.", "Because AWS requires it", "To save costs"], "a": 1},
        {"q": "When doing blue/green deployments with Terraform, what resource attribute is typically mapped to shift traffic?", "options": ["EC2 Instance type", "Route53 Weights or Target Group bindings", "Security Groups", "VPC ID"], "a": 1},
        {"q": "What is the primary role of the `.terraform.lock.hcl` file in a team environment?", "options": ["It locks the DynamoDB table", "It ensures that every developer and the CI/CD runner download the EXACT same provider hashes, preventing malicious updates or version drift.", "It encrypts the secrets", "It stops applies"], "a": 1},
        {"q": "Which of these is a valid architectural pattern for injecting secrets at scale without hardcoding `.tfvars`?", "options": ["Use `data \"aws_secretsmanager_secret_version\"` blocks to fetch them directly inside Terraform memory at execution time.", "Write them to a public wiki", "Put them in state", "Use default arguments"], "a": 0}
    ]
}

def inject():
    global text
    for ch_id, questions in q_bank.items():
        idx = text.find(f'"id": "{ch_id}"')
        if idx == -1: continue
        quiz_end = text.find('        ],', idx)
        if quiz_end == -1: continue
        
        # Build insertion string
        # check if there's already an item in the array
        block = text[idx:quiz_end]
        has_items = '{' in block[block.find('"quiz": ['):]
        
        insert_str = ""
        for q in questions:
            if not has_items and insert_str == "":
                insert_str += f'\n            {json.dumps(q)}'
            else:
                insert_str += f',\n            {json.dumps(q)}'
                
        text = text[:quiz_end] + insert_str + '\n' + text[quiz_end:]

inject()

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(text)

print("Part 1 Executed Successfully.")
